############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
# url = "about/"
weight = 2
hasChildren = true

  [[main]]
  parent = "About"
  name = "About Us"
  url = "about/"
  weight = 1
  
  [[main]]
  parent = "About"
  name = "Fleet"
  url = "fleet/"
  weight = 2
  
  [[main]]
  parent = "About"
  name = "Portfolio"
  url = "portfolio/"
  weight = 3
  
  [[main]]
  parent = "About"
  name = "Gallery"
  url = "gallery/"
  weight = 4

  [[main]]
  parent = "About"
  name = "Service"
  url = "service/"
  weight = 5

  [[main]]
  parent = "About"
  name = "Pricing"
  url = "pricing/"
  weight = 6


#[[main]]
#name = "Fleet"
#url = "fleet/"
#weight = 3

#[[main]]
#name = "Gallery"
#url = "gallery/"
#weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5

#[[main]]
#weight = 6
#name = "More"
#hasChildren = true

#  [[main]]
#  parent = "More"
#  name = "Service"
#  url = "service/"
#  weight = 1

#  [[main]]
#  parent = "More"
#  name = "Pricing"
#  url = "pricing/"
#  weight = 2

#  [[main]]
#  parent = "More"
#  name = "FAQ"
#  url = "faq/"
#  weight = 3
  
[[main]]
name = "Contact"
url = "contact/"
weight = 7


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Fleet"
url = "fleet/"
weight = 3

[[footer]]
name = "Portfolio"
url = "portfolio/"
weight = 4

[[footer]]
name = "Gallery"
url = "gallery/"
weight = 5

[[footer]]
name = "Blog"
url = "blog/"
weight = 6

#[[footer]]
#name = "Service"
#url = "service/"
#weight = 5

#[[footer]]
#name = "Pricing"
#url = "pricing/"
#weight = 6

[[footer]]
name = "FAQ"
url = "faq/"
weight = 7

[[footer]]
name = "Contact"
url = "contact/"
weight = 8
